sudo: false
language: node_js
node_js:
  - '10'

os: osx

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- npm run check-format
- npm run lint
- NODE_ENV=test npm nyc mocha

  # TODO - we need to add this to our releaserc exec to sign the build
  # https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html
  # export CERTIFICATE_P12=Certificate.p12;
  # echo $CERTIFICATE_OSX_P12 | base64 — decode > $CERTIFICATE_P12;
  # export KEYCHAIN=build.keychain;
  # security create-keychain -p mysecretpassword $KEYCHAIN;
  # security default-keychain -s $KEYCHAIN;
  # security unlock-keychain -p mysecretpassword $KEYCHAIN;
  # security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;



branches:
  except:
    - /^v\d+\.\d+\.\d+$/

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - semantic-release --debug

