sudo: false
language: node_js
node_js:
  - '10'

os: osx

install:
  - yarn install --verbose

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- yarn run check-format
- yarn run lint
- yarn run test-ci

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - scripts/keychain.sh

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - semantic-release --debug
