sudo: false
language: node_js
node_js:
  - '10'

os: osx

install:
  - npm install

script:
- npm run check-format
- npm run lint
- npm test

before_deploy:
  - npm run pack

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - semantic-release
