sudo: false
language: node_js
node_js:
  - '10'

os: osx

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

cache: 
  yarn: true

install:
  - npm install -g yarn
  - yarn install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
- yarn run check-format
- yarn run lint
- NODE_ENV=test nyc mocha

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

after_script:
  - ./cc-test-reporter after-build -t lcov --debug --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - scripts/keychain.sh

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - semantic-release --debug
