sudo: false
language: node_js
node_js:
  - '10'

os: osx

install:
  - npm install

script:
- npm run check-format
- npm run lint
- npm test


before_deploy:
  - npm run pack
  # https://www.jviotti.com/2016/03/16/how-to-code-sign-os-x-electron-apps-in-travis-ci.html
  # export CERTIFICATE_P12=Certificate.p12;
  # echo $CERTIFICATE_OSX_P12 | base64 — decode > $CERTIFICATE_P12;
  # export KEYCHAIN=build.keychain;
  # security create-keychain -p mysecretpassword $KEYCHAIN;
  # security default-keychain -s $KEYCHAIN;
  # security unlock-keychain -p mysecretpassword $KEYCHAIN;
  # security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;



branches:
  except:
    - /^v\d+\.\d+\.\d+$/

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - semantic-release --debug
     
